services:
  food-delivery-app:
    build:
      context: ./food-delivery-app
      dockerfile: Dockerfile
    container_name: microwatch-food-delivery-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - microwatch-net
    restart: unless-stopped

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: microwatch-payment-service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - microwatch-net
    restart: unless-stopped

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: microwatch-order-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - LOKI_HOST=http://loki:3100
      - PAYMENT_SERVICE_URL=http://payment-service:8002
    networks:
      - microwatch-net
    restart: unless-stopped


  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: microwatch-dashboard
    ports:
      - "3000:3000"
    environment:
      - VITE_PAYMENT_SERVICE_URL=http://payment-service:8002
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
      - VITE_PROMETHEUS_URL=http://prometheus:9090
      - VITE_JAEGER_URL=http://jaeger:16686
      - VITE_LOKI_URL=http://loki:3100
    depends_on:
      - payment-service
      - order-service
    networks:
      - microwatch-net

  prometheus:
    image: prom/prometheus:latest
    container_name: microwatch-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - microwatch-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: microwatch-jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - microwatch-net

  loki:
    image: grafana/loki:latest
    container_name: microwatch-loki
    ports:
      - "3100:3100"
    networks:
      - microwatch-net

networks:
  microwatch-net:
    driver: bridge
